<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="W-7FM3M13" failures="3" tests="6" name="Platform Sign Up" time="291.642" errors="0" timestamp="2020-11-18T18:11:40 IST">
  <testcase classname="com.test.testcases.PlatformSignUpTest" name="signUpConversationalAI" time="53.652">
    <skipped/>
  </testcase> <!-- signUpConversationalAI -->
  <testcase classname="com.test.testcases.PlatformSignUpTest" name="signUpConversationalAI" time="41.694">
    <failure type="java.lang.AssertionError" message="Success Message does not exist">
      <![CDATA[java.lang.AssertionError: Success Message does not exist
at com.utils.GenericUtils.checkFieldExist(GenericUtils.java:192)
at com.pages.SignUpCAIPage.verifySuccessMessage(SignUpCAIPage.java:141)
at com.test.testcases.PlatformSignUpTest.signUpConversationalAI(PlatformSignUpTest.java:62)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- signUpConversationalAI -->
  <testcase classname="com.test.testcases.PlatformSignUpTest" name="signUpConversationalAI" time="40.686">
    <skipped/>
  </testcase> <!-- signUpConversationalAI -->
  <testcase classname="com.test.testcases.PlatformSignUpTest" name="signUpConversationalAI" time="41.666">
    <failure type="java.lang.AssertionError" message="Success Message does not exist">
      <![CDATA[java.lang.AssertionError: Success Message does not exist
at com.utils.GenericUtils.checkFieldExist(GenericUtils.java:192)
at com.pages.SignUpCAIPage.verifySuccessMessage(SignUpCAIPage.java:141)
at com.test.testcases.PlatformSignUpTest.signUpConversationalAI(PlatformSignUpTest.java:62)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- signUpConversationalAI -->
  <testcase classname="com.test.testcases.PlatformSignUpTest" name="signUpConversationalAI" time="56.893">
    <skipped/>
  </testcase> <!-- signUpConversationalAI -->
  <testcase classname="com.test.testcases.PlatformSignUpTest" name="signUpConversationalAI" time="54.502">
    <failure type="java.lang.AssertionError" message="Success Message does not exist">
      <![CDATA[java.lang.AssertionError: Success Message does not exist
at com.utils.GenericUtils.checkFieldExist(GenericUtils.java:192)
at com.pages.SignUpCAIPage.verifySuccessMessage(SignUpCAIPage.java:141)
at com.test.testcases.PlatformSignUpTest.signUpConversationalAI(PlatformSignUpTest.java:62)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- signUpConversationalAI -->
</testsuite> <!-- Platform Sign Up -->
