<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="3" ignored="0" total="6" passed="0" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-11-12T21:50:43 IST" name="Platform Suite" finished-at="2020-11-12T21:57:23 IST" duration-ms="399816">
    <groups>
    </groups>
    <test started-at="2020-11-12T21:50:43 IST" name="Platform Sign Up" finished-at="2020-11-12T21:57:23 IST" duration-ms="399816">
      <class name="com.test.testcases.PlatformSignUpTest">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:com.test.testcases.PlatformSignUpTest@1cbb87f3]" started-at="2020-11-12T21:50:23 IST" name="beforeSuite" finished-at="2020-11-12T21:50:43 IST" duration-ms="20455" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:com.test.testcases.PlatformSignUpTest@1cbb87f3]" started-at="2020-11-12T21:50:44 IST" name="beforeMethod" finished-at="2020-11-12T21:50:44 IST" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method retried="true" signature="signUpConversationalAI(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.test.testcases.PlatformSignUpTest@1cbb87f3]" started-at="2020-11-12T21:50:44 IST" name="signUpConversationalAI" data-provider="data" finished-at="2020-11-12T21:51:52 IST" duration-ms="67385" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[Ramarajan]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Sampath]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[testdqefewfewf@sap.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Test$123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Success Message does not exist]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Success Message does not exist
at org.testng.Assert.fail(Assert.java:97)
at com.utils.GenericUtils.checkFieldExist(GenericUtils.java:192)
at com.pages.SignUpCAIPage.verifySuccessMessage(SignUpCAIPage.java:141)
at com.test.testcases.PlatformSignUpTest.signUpConversationalAI(PlatformSignUpTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpConversationalAI -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:com.test.testcases.PlatformSignUpTest@1cbb87f3]" started-at="2020-11-12T21:51:52 IST" name="afterMethod" finished-at="2020-11-12T21:51:52 IST" duration-ms="648" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:com.test.testcases.PlatformSignUpTest@1cbb87f3]" started-at="2020-11-12T21:51:52 IST" name="beforeMethod" finished-at="2020-11-12T21:51:52 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="signUpConversationalAI(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.test.testcases.PlatformSignUpTest@1cbb87f3]" started-at="2020-11-12T21:51:52 IST" name="signUpConversationalAI" data-provider="data" finished-at="2020-11-12T21:53:02 IST" duration-ms="69941" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Ramarajan]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Sampath]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[testdqefewfewf@sap.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Test$123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Success Message does not exist]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Success Message does not exist
at org.testng.Assert.fail(Assert.java:97)
at com.utils.GenericUtils.checkFieldExist(GenericUtils.java:192)
at com.pages.SignUpCAIPage.verifySuccessMessage(SignUpCAIPage.java:141)
at com.test.testcases.PlatformSignUpTest.signUpConversationalAI(PlatformSignUpTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpConversationalAI -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:com.test.testcases.PlatformSignUpTest@1cbb87f3]" started-at="2020-11-12T21:53:02 IST" name="afterMethod" finished-at="2020-11-12T21:53:03 IST" duration-ms="222" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:com.test.testcases.PlatformSignUpTest@1cbb87f3]" started-at="2020-11-12T21:53:03 IST" name="beforeMethod" finished-at="2020-11-12T21:53:03 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method retried="true" signature="signUpConversationalAI(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.test.testcases.PlatformSignUpTest@1cbb87f3]" started-at="2020-11-12T21:53:03 IST" name="signUpConversationalAI" data-provider="data" finished-at="2020-11-12T21:54:11 IST" duration-ms="68442" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[Sachin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Tendulkar]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[test1@sap.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Test$123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Success Message does not exist]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Success Message does not exist
at org.testng.Assert.fail(Assert.java:97)
at com.utils.GenericUtils.checkFieldExist(GenericUtils.java:192)
at com.pages.SignUpCAIPage.verifySuccessMessage(SignUpCAIPage.java:141)
at com.test.testcases.PlatformSignUpTest.signUpConversationalAI(PlatformSignUpTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpConversationalAI -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:com.test.testcases.PlatformSignUpTest@1cbb87f3]" started-at="2020-11-12T21:54:11 IST" name="afterMethod" finished-at="2020-11-12T21:54:11 IST" duration-ms="160" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:com.test.testcases.PlatformSignUpTest@1cbb87f3]" started-at="2020-11-12T21:54:11 IST" name="beforeMethod" finished-at="2020-11-12T21:54:11 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="signUpConversationalAI(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.test.testcases.PlatformSignUpTest@1cbb87f3]" started-at="2020-11-12T21:54:11 IST" name="signUpConversationalAI" data-provider="data" finished-at="2020-11-12T21:55:20 IST" duration-ms="68484" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Sachin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Tendulkar]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[test1@sap.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Test$123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Success Message does not exist]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Success Message does not exist
at org.testng.Assert.fail(Assert.java:97)
at com.utils.GenericUtils.checkFieldExist(GenericUtils.java:192)
at com.pages.SignUpCAIPage.verifySuccessMessage(SignUpCAIPage.java:141)
at com.test.testcases.PlatformSignUpTest.signUpConversationalAI(PlatformSignUpTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpConversationalAI -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:com.test.testcases.PlatformSignUpTest@1cbb87f3]" started-at="2020-11-12T21:55:20 IST" name="afterMethod" finished-at="2020-11-12T21:55:20 IST" duration-ms="182" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:com.test.testcases.PlatformSignUpTest@1cbb87f3]" started-at="2020-11-12T21:55:20 IST" name="beforeMethod" finished-at="2020-11-12T21:55:20 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method retried="true" signature="signUpConversationalAI(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.test.testcases.PlatformSignUpTest@1cbb87f3]" started-at="2020-11-12T21:55:20 IST" name="signUpConversationalAI" data-provider="data" finished-at="2020-11-12T21:56:23 IST" duration-ms="63343" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[Jan]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Gilg]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[test3@sap.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Test$123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Success Message does not exist]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Success Message does not exist
at org.testng.Assert.fail(Assert.java:97)
at com.utils.GenericUtils.checkFieldExist(GenericUtils.java:192)
at com.pages.SignUpCAIPage.verifySuccessMessage(SignUpCAIPage.java:141)
at com.test.testcases.PlatformSignUpTest.signUpConversationalAI(PlatformSignUpTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpConversationalAI -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:com.test.testcases.PlatformSignUpTest@1cbb87f3]" started-at="2020-11-12T21:56:23 IST" name="afterMethod" finished-at="2020-11-12T21:56:23 IST" duration-ms="143" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="signUpConversationalAI(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.test.testcases.PlatformSignUpTest@1cbb87f3]" started-at="2020-11-12T21:56:23 IST" name="signUpConversationalAI" data-provider="data" finished-at="2020-11-12T21:57:23 IST" duration-ms="59471" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Jan]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Gilg]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[test3@sap.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Test$123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Success Message does not exist]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Success Message does not exist
at org.testng.Assert.fail(Assert.java:97)
at com.utils.GenericUtils.checkFieldExist(GenericUtils.java:192)
at com.pages.SignUpCAIPage.verifySuccessMessage(SignUpCAIPage.java:141)
at com.test.testcases.PlatformSignUpTest.signUpConversationalAI(PlatformSignUpTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpConversationalAI -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:com.test.testcases.PlatformSignUpTest@1cbb87f3]" started-at="2020-11-12T21:56:23 IST" name="beforeMethod" finished-at="2020-11-12T21:56:23 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:com.test.testcases.PlatformSignUpTest@1cbb87f3]" started-at="2020-11-12T21:57:23 IST" name="afterMethod" finished-at="2020-11-12T21:57:23 IST" duration-ms="207" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:com.test.testcases.PlatformSignUpTest@1cbb87f3]" started-at="2020-11-12T21:57:23 IST" name="afterSuite" finished-at="2020-11-12T21:57:43 IST" duration-ms="20047" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.test.testcases.PlatformSignUpTest -->
    </test> <!-- Platform Sign Up -->
  </suite> <!-- Platform Suite -->
</testng-results>
